Repository ekino/v6y, pull requests merged in 2025-03, with the labels that each got.

#138 [FEATURE]: implemented MTTR and UTA functions with mock data
  v6y-apps/bfb-devops-auditor/src/__tests__/DoraMetricsUtils-test.ts
  v6y-apps/bfb-devops-auditor/src/auditors/dora-metrics/DoraMetricsAuditor.ts
  v6y-apps/bfb-devops-auditor/src/auditors/dora-metrics/DoraMetricsUtils.ts
  v6y-apps/bfb-devops-auditor/src/auditors/dora-metrics/mockDataDogEventsData.json
  v6y-apps/bfb-devops-auditor/src/auditors/types/DoraMetricsAuditType.ts
  v6y-libs/core-logic/src/config/AuditHelpConfig.ts
  v6y-libs/core-logic/src/config/DevOpsConfig.ts
  v6y-libs/core-logic/src/config/EvolutionHelpConfig.ts
  v6y-libs/core-logic/src/utils/DateUtils.ts
Labels: feature

#145 [FEATURE]: Integrated DataDog Api in Dora Metrics
  v6y-apps/bfb-devops-auditor/src/__tests__/DoraMetricsUtils-test.ts
  v6y-apps/bfb-devops-auditor/src/auditors/dora-metrics/DoraMetricsAuditor.ts
  v6y-apps/bfb-devops-auditor/src/auditors/dora-metrics/DoraMetricsUtils.ts
  v6y-apps/bfb-devops-auditor/src/auditors/types/DoraMetricsAuditType.ts
  v6y-libs/core-logic/src/__tests__/MonitoringUtils-test.ts
  v6y-libs/core-logic/src/__tests__/mockDataDogEventsData.json
  v6y-libs/core-logic/src/apis/MonitoringApi.ts
  v6y-libs/core-logic/src/database/models/ApplicationModel.ts
  v6y-libs/core-logic/src/index.ts
  v6y-libs/core-logic/src/types/ApplicationConfigType.ts
  v6y-libs/core-logic/src/types/ApplicationType.ts
  v6y-libs/core-logic/src/types/MonitoringType.ts
  v6y-libs/core-logic/src/types/index.ts
  v6y-libs/core-logic/src/utils/DateUtils.ts
  v6y-libs/core-logic/src/utils/MonitoringUtils.ts
  v6y-libs/core-logic/tsconfig.json
Labels: feature

#147 [FIX]: correct casing of types in Dora Metrics Auditor
  v6y-apps/bfb-devops-auditor/src/auditors/dora-metrics/DoraMetricsUtils.ts
  v6y-apps/bfb-devops-auditor/src/auditors/types/DoraMetricsAuditType.ts
Labels: bug

#148 [FIX]: update git organization field to be optional
  v6y-apps/bfb-static-auditor/src/auditors/dependencies-auditor/DependenciesAuditor.ts
  v6y-apps/bff/src/types/application/ApplicationCreateOrEditInput.ts
  v6y-apps/front-bo/public/locales/en/common.json
  v6y-apps/front-bo/public/locales/fr/common.json
  v6y-apps/front-bo/src/commons/config/VitalityFormConfig.tsx
  v6y-libs/core-logic/src/apis/RepositoryApi.ts
Labels: bug

#146 [REFACTOR]: update date parameters from string to Date in Dora Auditor and in APIs
  v6y-apps/bfb-devops-auditor/src/__tests__/DoraMetricsUtils-test.ts
  v6y-apps/bfb-devops-auditor/src/auditors/dora-metrics/DoraMetricsAuditor.ts
  v6y-apps/bfb-devops-auditor/src/auditors/dora-metrics/DoraMetricsUtils.ts
  v6y-apps/bfb-devops-auditor/src/auditors/types/DoraMetricsAuditType.ts
  v6y-libs/core-logic/src/__tests__/MonitoringUtils-test.ts
  v6y-libs/core-logic/src/apis/MonitoringApi.ts
  v6y-libs/core-logic/src/apis/RepositoryApi.ts
  v6y-libs/core-logic/src/types/MonitoringType.ts
  v6y-libs/core-logic/src/types/RepositoryType.ts
  v6y-libs/core-logic/src/utils/MonitoringUtils.ts
Labels: enhancement

#151 feature : added DORA metrics audit reports in the frontend
  v6y-apps/bfb-devops-auditor/src/__tests__/DoraMetricsUtils-test.ts
  v6y-apps/bfb-devops-auditor/src/auditors/dora-metrics/DoraMetricsUtils.ts
  v6y-apps/front/src/commons/config/VitalityCommonConfig.tsx
  v6y-apps/front/src/features/app-details/components/audit-reports/VitalityAuditReportsTypeGrouper.tsx
  v6y-apps/front/src/features/app-details/components/audit-reports/auditors/dora/VitalityDoraReportItem.tsx
  v6y-apps/front/src/features/app-details/components/audit-reports/auditors/dora/VitalityDoraReportsGrouper.tsx
Labels: feature

#127 [FEATURE] : extends the static auditor to add Bundle Analyze
  pnpm-lock.yaml
  v6y-apps/bfb-static-auditor/package.json
  v6y-apps/bfb-static-auditor/src/auditors/StaticAuditorManager.ts
  v6y-apps/bfb-static-auditor/src/auditors/bundle-analyzer/BundleAnalyzeAuditor.ts
  v6y-apps/bfb-static-auditor/src/auditors/bundle-analyzer/BundleAnalyzeUtils.ts
  v6y-apps/bfb-static-auditor/src/workers/BundleAnalyzeWorker.ts
  v6y-libs/core-logic/src/__tests__/AuditUtils-test.ts
  v6y-libs/core-logic/src/core/AuditUtils.ts
Labels: Review is Welcome
